name: IDMarinas Template Bundle Test Suite

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    branches: [ master ]
    types: [ opened, synchronize, reopened ]
    tags-ignore: [ dependencies, documentation, meta, 'docker configuration', 'deployer configuration' ]
  push:
    branches: [ master ]
    paths-ignore:
      - '.deployer/**'
      - '.docker/**'
      - '.idea/**'
      - 'migrations/**'
      - '**/docs/**'
      - '**/Writerside/**'
      - '**/README.md'
      - '**/COMMANDS.md'
      - '**/TIPS.md'
      - '**/TODO.md'
      - '**/LICENSE'
      - rector.php
      - .editorconfig
      - .gitignore
      - compose.yaml

jobs:
  build:
    runs-on: ubuntu-latest
    name: PHP ${{ matrix.php }} and Symfony ${{ matrix.symfony }}
    strategy:
      matrix:
        php: [ '8.3', '8.4' ]
        symfony: [ '6.4.*', '7.1.*', '7.2.*' ]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: ${{ (matrix.php == '8.2' && matrix.symfony == '6.4.*') && '0' || '1' }}

      - name: Setup PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: flex

      - name: Download dependencies
        env:
          SYMFONY_REQUIRE: ${{ matrix.symfony }}
        uses: ramsey/composer-install@v3

      # # Uncomment if need create a SQLite Database
      # - name: Create Database SQLite
      #   run: 'php bin/console doctrine:schema:create --env=test && php bin/console doctrine:fixtures:load --env=test -n'

      - name: Run test suite on PHP ${{ matrix.php }} and Symfony ${{ matrix.symfony }}
        run: ./vendor/bin/phpunit --exclude ignore

      # # Uncomment to activate SonarCloud Scan
      # - name: SonarCloud Scan
      #   if: matrix.php == '8.2' && matrix.symfony == '6.4.*'
      #   uses: SonarSource/sonarqube-scan-action@v4
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
